version: 2

jobs:
  check:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit

    steps:
      steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "deps.edn"}}

        - run:
            name: Running unit tests
            command: clojure -A:test

        - save_cache:
            paths:
              - ~/.m2
              - ~/.cognitect-s3-libs
            keys: v1-dependencies-{{ checksum "deps.edn"}}
